### ISSUE TITLE
typos of some codes

### ISSUE THREAD

**Issue by JoJoistheBestOne** [VivienCabannes/laplacian#1]
Dear Authors.
recently, I read about your very talented work, and just try some then what I got below, hopefully it will help.

https://github.com/VivienCabannes/laplacian/blob/master/src/pssl/architecture/mlp.py#L41        the list -> List
https://github.com/VivienCabannes/laplacian/blob/master/src/pssl/datasets/halfmoon.py#L53        the list -> List
https://github.com/VivienCabannes/laplacian/blob/master/src/pssl/datasets/halfmoon.py#L53        the torch.pi -> torch.tensor(math.pi)

**Comment by VivienCabannes** [comment]
Thank you very much.
Note that since python 3.9, the type list can be used directly (without invoking typing.List, which is now depreciated https://docs.python.org/3/library/typing.html#typing.List).
Pytorch has now a support for pi, so you can use torch.pi. I do not know in which version this was introduced.

I should definitely add requirements asking for Python 3.9 or newer, and for the right versions of pytorch.

Hope this helps
Vivien

**Comment by VivienCabannes** [comment]
Closing this comment, do not hesitate to open a pull-request adding special requirements regarding pytorch version, and eventually continuous integration to check installation with pip.
NB: Requiring python 3.9 or + for type linting purposes only would be of little interest.
